from . import assets_request
from . import processor_type
from . import generation
from . import equipment_inherit
from . import hr_emp_inherit
from . import hr_emp_public
from . import maintenance_inherit
from . import operating_system
from . import device_company
from . import res_partner_inherit
from . import main_asset_category
from . import maintenance_equipment_category_inherit
