# -*- coding: utf-8 -*-
{
    'name': "Asset Management",
    'summary': """Assets management""",
    'author': "My Company",
    'website': "http://www.yourcompany.com",
    'category': 'Uncategorized',
    'version': '16.0.1',
    'depends': ['base','hr','maintenance','hr_maintenance',],
    'license': 'LGPL-3',
    'data': [
        'security/user_groups.xml',
        'security/ir_rules.xml',
        'security/ir.model.access.csv',
        'report/allocation_report.xml',
        'report/return_assets_report.xml',
        'report/equipment_asset_report.xml',
        'report/asset_request_report.xml',
        'report/asset_maintenance_request.xml',
        'data/ir_sequence.xml',
        'data/ir_server_action.xml',
        'data/equipment_category_demo_data.xml',
        'data/all_assets_request_mail_templates.xml',
        'data/assets_request_mail_template.xml',
        'data/assets_allocated_mail_template.xml',
        'data/return_assets_mail_template.xml',
        'data/assets_req_refuse_mail_template.xml',
        'data/maintenance_mail.xml',
        'views/assets_request_view.xml',
        'views/generation.xml',
        'views/processor_type.xml',
        'views/equipment_inherit.xml',
        'views/hr_employee_inherit.xml',
        'views/hr_employee_public_inherit.xml',
        'views/maintenance_request_inherit.xml',
        'views/equipment_category_inherit.xml',
        'views/operating_system.xml',
        'views/device_company.xml',
        'views/res_partner_inherit.xml',
        'views/main_asset_category.xml',
        'wizard/return_asset_detail.xml',
        'wizard/import_asset_list.xml',
        'wizard/employee_receive_assets.xml',
        'wizard/equipment_report.xml',
        'wizard/asset_request_report.xml',
        'wizard/asset_maintenance_report.xml',
        'views/menu.xml',
    ],
}
